version : '3.5'

# test the configuration as follows:

# docker run --net=oda --rm confluentinc/cp-kafka bash -c "seq 42 | kafka-console-producer --request-required-acks 1 --broker-list kafka:9092 --topic foo && echo 'Produced 42 messages.'"
# docker run --net=oda --rm confluentinc/cp-kafka kafka-console-consumer --bootstrap-server kafka:9092 --topic foo --from-beginning --max-messages 42

services:

  zookeeper:
    image: "confluentinc/cp-zookeeper"
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181 

  kafka:
    image: "confluentinc/cp-kafka"
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

      # comment if running a multiple nodes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# uncomment below to start multiple kafka nodes

#  kafka_1:
#    image: "confluentinc/cp-kafka"
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1:9092

#  kafka_2:
#    image: "confluentinc/cp-kafka"
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_2:9092

  kafka_rest:
    image: "confluentinc/cp-kafka-rest"
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka
    environment: 
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_HOST_NAME=kafka_rest

  ksql_server:
    image: "confluentinc/cp-ksql-server"
    restart: always
    depends_on:
      - kafka_rest
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
      - KSQL_LISTENERS=http://0.0.0.0:8088/
      - KSQL_KSQL_SERVICE_ID=ksqlserver

  nimbus:
    image: storm
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  supervisor:
    image: storm
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always

  stormui:
    image: storm
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    ports:
      - "8080:8080"


networks:
  default:
    name: oda





